### ISSUE TITLE
Runtime error when running with dace_gpu

### ISSUE THREAD

**Issue by luise1030** [spcl/npbench#16]
**Description:**
I got a runtime error when running the **jacobi_1d** case with **dace_gpu**. It seems to be due to the wrong data type for the input array.

**To Reproduce:**
_python3 run_benchmark.py -b jacobi_1d -f dace_gpu_

***** Testing DaCe GPU with jacobi_1d on the S dataset *****
NumPy - default - validation: 8ms
Traceback (most recent call last):
  File "run_benchmark.py", line 57, in <module>
    test.run(args["preset"], args["validate"], args["repeat"], args["timeout"], False)
  File "/dockerx/LRZ/npbench/npbench/infrastructure/test.py", line 100, in run
    frmwrk_out, _ = first_execution(impl, impl_name)
  File "/dockerx/LRZ/npbench/npbench/infrastructure/timeout_decorator.py", line 65, in inner
    result = fn(*args, **kwargs)
  File "/dockerx/LRZ/npbench/npbench/infrastructure/test.py", line 93, in first_execution
    return self._execute(self.frmwrk, impl, impl_name, "first/validation", context, 1, ignore_errors)
  File "/dockerx/LRZ/npbench/npbench/infrastructure/test.py", line 37, in _execute
    '__npb_result')
  File "/dockerx/LRZ/npbench/npbench/infrastructure/utilities.py", line 140, in benchmark
    output = timeit.repeat(stmt, setup=setup, repeat=repeat, number=1, globals=ldict)
  File "/opt/conda/lib/python3.7/timeit.py", line 238, in repeat
    return Timer(stmt, setup, timer, globals).repeat(repeat, number)
  File "/opt/conda/lib/python3.7/timeit.py", line 205, in repeat
    t = self.timeit(number)
  File "/opt/conda/lib/python3.7/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/opt/conda/lib/python3.7/site-packages/dace/codegen/compiled_sdfg.py", line 304, in __call__
    argtuple, initargtuple = self._construct_args(kwargs)
  File "/opt/conda/lib/python3.7/site-packages/dace/codegen/compiled_sdfg.py", line 370, in _construct_args
    (type(arg).__name__, a))
**TypeError: Passing an object (type ndarray) to an array in argument "A"**

**OS:** Ubuntu 20.04.4 LTS
**Docker image:** rocm/pytorch:rocm5.4.1_ubuntu20.04_py3.7_pytorch_1.12.1
**DaCe:** 0.14.2  (via **python3 -m pip install dace**)
**NPBench:** f18e3c7105b6d664b031a4f35a723645410a5810

**Comment by luise1030** [comment]
After investigation, it is due to the lack of **__cuda_array_interface__** support.

**Comment by tbennun** [comment]
Which object is lacking cuda_array_interface?

**Comment by luise1030** [comment]
The input ndarray created by cupy. It returns False in the check of **dace.dtypes.is_array()** as in https://github.com/spcl/dace/blob/master/dace/dtypes.py#L1480

Non-supported **__cuda_array_interface__** on ROCM/HIP:
https://github.com/ROCmSoftwarePlatform/cupy/blob/master/cupy/_core/core.pyx#L245.
